### ISSUE TITLE
VS Hangs with multiple class selectors in CSS editor

### ISSUE THREAD

**Issue by jfollas** [madskristensen/WebEssentials2013#1045]
To reproduce in VS2013 Update 2 (RTM):

I started with this CSS rule:

``` css
table.default {
    background-image: url(/images/default/default.png);
}
```

Then copied and pasted twice because I was going to add a third class to each of the new selectors. VS hangs after trying to edit one of the pastings to add the additional class name:

``` css
table.default {
    background-image: url(/images/default/default.png);
}
table.default.stand {
    background-image: url(/images/default/stand.png), url(/images/default/default.png);
}

table.default.hit {
    background-image: url(/images/default/hit.png), url(/images/default/default.png);
}
```
