### ISSUE TITLE
SASS: Unable to compile CSS with @include

### ISSUE THREAD

**Issue by Voo2** [madskristensen/WebEssentials2013#1058]
Hello,

I'm using VS 2013 Update 2 RC + WebEssentials 2013 for Update 2 RC. I has this scss file

``` scss
#bla {
    width: 80%;
    margin-right: auto;
    margin-left: auto;
    font-size: .8em;
    background: #fefe8a;
    padding: 20px;
    border: 1px solid black;
    border-radius: 20px;
    /*@include opacity(0.8);*/
}


@mixin opacity($opacity) {
  opacity: $opacity;
  $opacity-ie: $opacity * 100;
  filter: alpha(opacity=$opacity-ie); //IE8
}
```

As soon as I remove the comment, the css file will no longer compile. No mixin can I use with include.

Error   1   no mixin named opacity
Backtrace:  D:\Entwicklung\Tutorials\SASS\styles.scss   12  2   SASS
