### ISSUE TITLE
NullReferenceException in ProcessGeneratedMaps

### ISSUE THREAD

**Issue by MarcelRaad** [madskristensen/WebEssentials2013#1078]
As mentioned in #1044 (and more recently #1064 by @skrysmanski) I always get the following the error message when compiling a certain LESS file with Web Essentials 2013 v2.1:

An exception was thrown when collecting maps: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.CssSourceMap.ProcessGeneratedMaps(String cssfileContents)
   at MadsKristensen.EditorExtensions.CssSourceMap.<CollectRules>d__10.MoveNext()

I could finally reduce the LESS file to the following lines:

``` less
.mCS-black &>.mCSB_scrollTools .mCSB_dragger:active .mCSB_dragger_bar,
.mCS-black &>.mCSB_scrollTools .mCSB_dragger.mCSB_dragger_onDrag .mCSB_dragger_bar
{
 background: #333333;
 background:rgba(0,0,0,0.9);
}
```

I can also post my WebEssentials-Settings.json if that makes a difference.
