### ISSUE TITLE
Sort Properties in LESS throws ArgumentOutOfRangeException with nested media query

### ISSUE THREAD

**Issue by rrharvey** [madskristensen/WebEssentials2013#1185]
If you try to sort properties of a LESS class with a nested media query an ArgumentOutOfRangeException is throw which crashes Visual Studio.

Example:

``` css
.container {
    display: block;

    @media (min-width: 768px) {
        display: none;
    }
}
```
