### ISSUE TITLE
Using less property merges interferes with autocomplete and syntax highlighting

### ISSUE THREAD

**Issue by ghost** [madskristensen/WebEssentials2013#1372]
It looks like WE doesn't recognize LESS's admittedly weird [merge syntax](http://lesscss.org/features/#merge-feature).

In a LESS file with these two lines:

``` less
@my-color: orange;
.doodad {background+_: @my-color;}
```

The editor will identify the plus as a syntax problem, and after typing it, you won't get any autocomplete or highlighting for @my-color.
