### ISSUE TITLE
Foundation help text error

### ISSUE THREAD

**Issue by dotnetchris** [madskristensen/WebEssentials2013#1483]
Given the following html/css

``` html
<div class="column"></div>
```

Web Essentials states 'When using columns you must also specify the class small-#, medium-#, or large-#.

Unless this varies depending on version, this is not an accurate statement. There is no need to apply a column-# when it will be the full width small-12 merely applies the styles

``` css
.row .small-12 {
    position: relative;
    width: 100%;
}
```

However note in the base styles:

``` css
.row .column, .row .columns {
    position: relative;
    padding-left: .9375em;
    padding-right: .9375em;
    width: 100%;
    float: left;
}
```

Both position relative and width 100% are already set. There is nothing gained by supplying small-12, medium-8, or large-6.

I'm not really sure what's the proper solution to this. You could clearly remove this rule, but I also see the value in it acknowledging the column sizing classes. Perhaps you could make this present a smaller or less forceful squiggly line? 

Resharper has the ability to configure it's inspection rules severity that something can be listed as "Hint" that only puts a small marker at the start of the code as opposed to squiggly lining the entire item as it would for an error.
