### ISSUE TITLE
Autoprefixer removig blank lines

### ISSUE THREAD

**Issue by hydandata** [madskristensen/WebEssentials2013#1748]
Selecting "Add Missing Standard Properties" or "Add Missing Vendor Specifics" from Web Essentials context menu causes empty lines to be removed from the containing definition, even when no changes are required. For example:

Before:
```css
.row {
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    
    -ms-flex: 0 1 auto;
    flex: 0 1 auto;
}
```

After:
```css
.row {
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;   
    -ms-flex: 0 1 auto;
    flex: 0 1 auto;
}
```
