### ISSUE TITLE
Sprite bundle should apply background-url and background-position instead of background

### ISSUE THREAD

**Issue by JasonKaz** [madskristensen/WebEssentials2013#1793]
This is an example of my generated SCSS file for a sprite bundle:
```SCSS
@mixin sprite-check() {           
    width: 22px;        
    height: 22px;  
    background: url('icons.png') -1px -24px;  
}
```

The icons in my spritesheet have a transparent background because I would like to apply a background color via CSS instead of it being in the image directly. To accomplish this now I need to add an !important to the background color like this:
```SCSS
[class^="icon-"],
[class*=" icon-"] {
	background-color: #000 !important; // Without the !important the background-color is overridden by Web Essentials' setting the sprite through "background"
}

.icon-check {
    @include sprite-check();
}
```

If Web Essentials were to set the image and position through background-url and background-position I wouldn't need to add the !important.
