### ISSUE TITLE
Sass not compiling

### ISSUE THREAD

**Issue by santypr** [madskristensen/WebEssentials2013#1824]
Some days ago my sass files are not compiling any more
![capture](https://cloud.githubusercontent.com/assets/7237337/6916142/a307d332-d791-11e4-8ac8-6598193b544f.PNG)
There's no error in my file and no log in Visual Studio Console, so I don't know whay it's not compiling

**Comment by am11** [comment]
I think you need to terminate node process either from task manager, or in powershell by running `stop-process -name node` before pressing Ctrl+S in VS.

**Comment by santypr** [comment]
Thanks am11. It didn't work :( Any other idea?

**Comment by am11** [comment]
I tested with WE v2.5.3 and it rendered the file correctly:

Input:

```scss
.dropdown-box {
    background: #cecece;

    .dropdown-items {
        border-bottom: 1px solid #a0a0a0;

        .item {
            height: 24px;
        }
    }

    .dropdown-expand {
        .expand-dot {

        }

        .expand-test {
        }
    }
}
```

Output:

```css
.dropdown-box {
  background: #cecece; }
  .dropdown-box .dropdown-items {
    border-bottom: 1px solid #a0a0a0; }
    .dropdown-box .dropdown-items .item {
      height: 24px; }

/*# sourceMappingURL=index.css.map */
```

Also tested with latest node-sass separately and same result was produced. 

Also, same result was produced with `ruby-sass` (VS > Tools > Options > Web Essentials > SASS > Use Ruby Runtime > True)

@davidtme, on a related note, would be nice if ruby-sass also make use of [OutputStyle option](https://github.com/madskristensen/WebEssentials2013/blob/1ab187317b07d195191a56995abffac54f2d359b/EditorExtensions/Resources/server/services/srv-scss.js#L13). This option used to have no effect in node-sass as libsass only used to generate nested output. Recently libsass added ability to have all formats works as ruby-sass. Subsequent versions of node-sass (current v3 beta) now support various output styles.
