### ISSUE TITLE
Error formating valid less expression

### ISSUE THREAD

**Issue by D4rkTiger** [madskristensen/WebEssentials2013#1869]
Hi,

I've written this expression :

<pre>
.generate-titleH(@n, @i: 1, @dec: 1) when (@i =< @n) {
  h@{i} {
    font-size: (@font-size-title - ((@i - 1) * @dec));
  }
  .generate-titleH(@n, (@i + 1), @dec);
}
</pre>

And when I want to apply auto-formatting, it was transformed to this :

<pre>
.generate-titleH(@n, @i: 1, @dec: 1) when (@i =< @n) {
    h@ {
        i;
    }

{
    font-size: (@font-size-title - ((@i - 1) * @dec));
}

.generate-titleH(@n, (@i + 1), @dec);
}
</pre>

The LESS compiler doesn't recognize the <strong>h@{i}</strong> as valid.

**Comment by madskristensen** [comment]
@mlorbetske Do you know if this is fixed in VS? I can repro it in VS2015 RC

**Comment by mlorbetske** [comment]
@madskristensen With RTM bits this is what I get on format:

```less
.generate-titleH(@n, @i: 1, @dec: 1) when (@i =< @n) {
    h@{i} {
        font-size: (@font-size-title - ((@i - 1) * @dec));
    }

    .generate-titleH(@n, (@i + 1), @dec);
}
```
