### ISSUE TITLE
Glyphs compiled incorrectly

### ISSUE THREAD

**Issue by joneff** [madskristensen/WebEssentials2013#1965]
This bug has already been fixed with sass/libsass#1231

But in essence, while the following compiles correctly:
```scss
.icon:before {
	content: "\e000";
}
```
If you assign `\e000` to a variable and then use it you get unexpected output:
```scss
$char: "\e000";

.icon:before {
	content: $char;
}
```
```css
@charset "UTF-8";
.icon:before {
  content: ""; }
```
