### ISSUE TITLE
Compilation with ruby runtime does not respect settings for output style and source map

### ISSUE THREAD

**Issue by joneff** [madskristensen/WebEssentials2013#1966]
Even with the simplest of cases:

```scss
// output style nested
// process sourcemap false

// scss
body {
	color: red;
}

// expected
body {
  color: blue; } // << EOF

// actual
body {
  color: red;
}

/*# sourceMappingURL=styles.css.map */ // << EOF
```
