### ISSUE TITLE
LESS compilation breaks when imbedding images as data urls

### ISSUE THREAD

**Issue by sultin** [madskristensen/WebEssentials2013#295]
Using the web essentials helper to imbed a small image into the css caused the less compiler to fail with no warning, my css file was just empty, and the preview panel is ghosted.

Code that broke the compiler:

``` css
body {
p {
background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAIAAADZrBkAAAAAK3RFWHRDcmVhdGlvbiBUaW1lAEZyaSA2IE1heSAyMDExIDA3OjUyOjIxIC0wNjAw42iMYQAAAAd0SU1FB9sFCg04G4ZSzxwAAAAJcEhZcwAAHsEAAB7BAcNpVFMAAAAEZ0FNQQAAsY8L/GEFAAAC9UlEQVR42l1TzU8TQRTvTGdb2gBt+Sgs1YIYIYQImiagIH4EDCYEQ4yevfkv6M3ExIvxoGcSEw8SDmBQIyRoQPmKEBBJQMo3LRTa0hZod6l0d2Z9OwWDvMNkd977zXvv93sPjY6OiqKIMTacMMRN43byEk7GWDAYJOBglDkcDu4x6HhmSCkKVVViIkYwbKSMYYQVJYUMaH9/LxqNEv0BjSmKYrFY4L14QtreDq2s+VbXN8vLzhUV5rtE0WG3K6oyNj5dWuyiVIGEOsygaQgjVVVX13zvP/Z39E0wZiQCkQ8HzYjda7x0v63Z7w909Aw8e/LIqFdq0GEatMG0Zd/6y9dv53y79Z6qOk+F6MzZicUnpr0z3o3J5+3WDLMzz4F5w0cw+EkkpL4vI3Mb8btNtW0tN0rOilZLxmEqVeupfNXevbcvaYwJghkgPBmHQa07kd3BcW9VeUnrnfqLFaWUqpQphCDvwmIiLiFsZBpSGYNURzCgQaU0urufTKGa6vNuVwHQQykF3+iPqa9DUy4xDxOBUZqdaQZageGjbBDn3wwRbMi1WTNMgo7RdDHqrniuX6vVFeSlQSpgH0TjME0TCCl2F1GmhSIxOXmQnZUFkgAS4vkT2uFhyoiRIAjsWH8MJ0hst2WazcLY5LzPF4BojNIt6Gz5/JuPn77o7P4kyTK/ZxzG2XHm5d6sqZhZDnV96J/97U3IMvQgywdLK6udXb3vhhY3ApHknxQv9R+TlNmyLS23r84u+Lq/zS+tbTU2XD4jOsOR2MDIz18r0ebq8uamhpwcuyxJ6SrR8PCwg5vJZF7zb/f0fn/zeTwYioEsBoTt+dkPmzwPWm+VXSgmRpyIx4Mh3Y5gdrsdZpIQIS7JwVBk3R9c9W+7Xc5St1hYkGezZWqgpKZJCYmjQiS9ILIMFB7AN9Clh2VZK8vdhBCzCahWd8JhnQGMmK4nHy6YRliEZDJ5ct8wNxgoWJlTe8j4rJDAViAcDrP/3Wlx0bEMpwzu/wIP0K4+kv3OfQAAAABJRU5ErkJggg==') /*images/reload.png*/;
*background-image: url(images/reload.png); /* For IE 6 and 7 */
}
}
```

Edit: sorry about the formatting.
