### ISSUE TITLE
LESS editor doesn't understand media queries inside style rules

### ISSUE THREAD

**Issue by madve2** [madskristensen/WebEssentials2013#302]
One of the nice features of less is that you can put media queries inside style rules so that you can put media-dependent changes right where they belong, ie.:

``` Less
nav {
    width:450px;
    margin-right: 55px;
    @media screen and (min-width: 1250px) {
        margin-right: 110px;
    }
}
```

Thankfully, the output is correctly generated:

``` css
nav {
    width: 450px;
    margin-right: 55px;
}

@media screen and (min-width: 1250px) {
    nav {
        margin-right: 110px;
    }
}
```

However, the VS editor doesn't like this sort of thing at all:
![2013-12-11--1412_001](https://f.cloud.github.com/assets/1123672/1723916/7cab72f0-6264-11e3-8de8-c321145054a9.png)

Please fix that if you can.
Thanks!
