### ISSUE TITLE
Full selector tooltip no showing on nested LESS selectors

### ISSUE THREAD

**Issue by madskristensen** [madskristensen/WebEssentials2013#371]
Example:

``` less
header{
    div{
        display: block;
    }
}
```

When hovering over the `div` selector, no tooltip shows the full path: `header div`. However, hovering the `display` declaration will. The tooltip should only show on selectors and not on declarations
