### ISSUE TITLE
SCSS processor should trigger with dependencies are changed

### ISSUE THREAD

**Issue by getfishtank** [madskristensen/WebEssentials2013#557]
If this file is changed...

``` SCSS

// _variables.scss
$dark-grey: #333333;

```

This file should be triggered for re-processing...

``` SCSS

// main.scss
@import "variables"

h1 { color: $dark-grey; }

```

I currently have to re-save main.scss to trigger a rebuild
