### ISSUE TITLE
CSS sort all properties deletes lines

### ISSUE THREAD

**Issue by shayc** [madskristensen/WebEssentials2013#790]
Try to sort the following CSS (Shift+Alt+S), the second line will be deleted.

``` css
.clearfix:before,
.clearfix:after {
  content: " "; /* 1 */
  display: table; /* 2 */
}
```
