### ISSUE TITLE
CSS minifier converts unicode values to a character

### ISSUE THREAD

**Issue by munjalpatel** [madskristensen/WebEssentials2013#813]
I have this in my CSS:

``` CSS
.fa-glass:before {
  content: "\f000";
}
```

It gets minified to this:

``` CSS
.fa-glass:before{content:""}
```

This obviously does not work when rendered in the browser. The minifier should keep "\f000" part intact.

I am on Visual Studio Ultimate 2013 Update 1 and Web Essentials 2013 v1.9
