### ISSUE TITLE
Quotes in Sass WE2013

### ISSUE THREAD

**Issue by joneff** [madskristensen/WebEssentials2013#880]
Quotes behaviour is rather strange Sass w/ WE2013 -- at times they are added at times removed. Examine the following code

``` sass
$q: unquote('"');
$p1: unquote("(");
$p2: unquote(")");
$c: "something";

body {
    test: $p1 + $q + $p2;
    test: $q + $p1 + $p2;
    test: unquote('"') + asd;
}
```

if I run it against sass console I get the expected output:

``` css
body {
  test: (");
  test: "();
  test: "asd; }
```

where as with WE i get:

``` css
body {
  test: ();
  test: "()";
  test: "asd"; }
```

So to sum up when doing string + string
- quotes in the begging of the line are preserved
  *\* if an end quote is missing, it's added
- if there is no quote in the beginning, they are stripped
